# Generated by Django 5.2.16 on 2026-07-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0004_special_booking_payment_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="flutterwave_payment_plan_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="booking",
            name="flutterwave_subscription_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="booking",
            name="next_billing_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="subscription_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
