# Generated by Django 5.2.17 on 2026-09-09 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_sessionnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('flexible', 'Flexible booking'), ('recurring', 'Monthly (recurring) booking')], max_length=20)),
                ('booking_id', models.UUIDField()),
                ('session_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Session Reminder',
                'verbose_name_plural': 'Session Reminders',
                'unique_together': {('kind', 'booking_id', 'session_date')},
            },
        ),
    ]
