# Generated by Django 5.2.17 on 2026-09-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_sessionreminder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessionreminder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sessionreminder',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sessionreminder',
            name='kind',
            field=models.CharField(choices=[('flexible', 'Flexible booking'), ('recurring', 'Monthly (recurring) booking'), ('special', 'Special booking')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='sessionreminder',
            unique_together={('kind', 'booking_id', 'session_date', 'session_key')},
        ),
    ]
