# Generated by Django 5.2.17 on 2026-10-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_alter_sessionreminder_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='end_time2',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time2',
            field=models.TimeField(null=True),
        ),
    ]
