# Generated by Django 6.0.6 on 2026-07-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_qtaker_last_answer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='qtaker',
            name='scored_question_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
