# Generated by Django 6.0.6 on 2026-07-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_qtaker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qtaker',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qtaker',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
