# Generated by Django 5.2.16 on 2026-08-04 06:16

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0005_alter_qtaker_age_alter_qtaker_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
    ]
