# Generated by Django 5.2.16 on 2026-08-04 10:30

from django.db import migrations, models


def approve_existing_questions(apps, schema_editor):
    """Keep existing questions live after the approval gate is introduced."""
    Question = apps.get_model("quiz", "Question")
    Question.objects.update(is_approved=True)


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0006_alter_question_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(approve_existing_questions, migrations.RunPython.noop),
    ]
