# Generated by Django 5.2.16 on 2026-08-27 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_question_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='fen',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='question',
            name='motif',
            field=models.CharField(blank=True, choices=[('mate_in_1', 'Mate in 1'), ('mate_in_2', 'Mate in 2'), ('pins', 'Pins'), ('forks', 'Forks'), ('skewers', 'Skewers'), ('discovered_attacks', 'Discovered Attacks'), ('endgames', 'Endgames'), ('openings', 'Openings'), ('tactics', 'Tactics')], default='mate_in_1', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='solution_uci',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=100),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='motif',
            field=models.CharField(blank=True, choices=[('mate_in_1', 'Mate in 1'), ('mate_in_2', 'Mate in 2'), ('pins', 'Pins'), ('forks', 'Forks'), ('skewers', 'Skewers'), ('discovered_attacks', 'Discovered Attacks'), ('endgames', 'Endgames'), ('openings', 'Openings'), ('tactics', 'Tactics')], default='mate_in_1', max_length=100),
        ),
        migrations.CreateModel(
            name='QuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_given', models.CharField(blank=True, default='', max_length=2000)),
                ('correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qtaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.qtaker')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.question')),
            ],
        ),
    ]
