# Generated by Django 5.2.17 on 2026-09-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_question_difficulty_question_fen_question_motif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='question',
            name='motif',
        ),
    ]
