# Generated by Django 5.2.17 on 2026-09-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_badge_userbadge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='motif',
            field=models.CharField(blank=True, choices=[('mate_in_1', 'Mate in 1'), ('mate_in_2', 'Mate in 2'), ('pins', 'Pins'), ('forks', 'Forks'), ('skewers', 'Skewers'), ('discovered_attacks', 'Discovered Attacks'), ('endgames', 'Endgames'), ('openings', 'Openings'), ('tactics', 'Tactics')], default='', max_length=100),
        ),
    ]
