# Generated by Django 5.2.16 on 2026-07-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="coach_tour_seen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="student_tour_seen",
            field=models.BooleanField(default=False),
        ),
    ]
